# Keywords:
# _d, _j, _i, _b, _
# _d : dependencies
# _j : jobs
# _i : inherits
# _b : bundles
# _ : Refers to the "head element", for example, in linux-recipe, these 2 objects are the same:
# 
# a: "Some arguments"
#
# a:
#   _: "Some arguments"

# terminology:
# Layers: every layers can have constants and objects
# objects can only inherits from layers to layers rather than with in a layer. 
- config: # This is a layer. 
  sh: zsh # Define some constants 
  pcm: yay

- tasks: 
  pacman: # Notice: `pcm` here is only a alias while `pacman` is a task.
      _j:
        - "{pcm} -S {{_}}"
  shell: # Define some objects that can inherits. When All "{}" are filled, the dependencis & jobs will starts. 
      _j:
        - "{sh} {{_}}"
  yarn:
      _d:
        - "{pcm} -S nodejs yarn"
      _j: 
        - "yarn global add {{_}}"
  pip: 
      _d:
        - "{pcm} -S python python-pip"
      _j:
        - "pip install {{_}}"
  git: 
      _d: 
        - "{pcm} -S git"
      _j:
        - "git clone {{_}} {{dir}}"
  stow:
      _d: 
        - "{pcm} -S stow"
      _j:
        - "stow -d {{stow}} -t {{target}} -S {{_}}"

- softwares:
    _b: # Inherits through _b (bundle), this usually works for multiple tasks that have same options.
      pacman: [
                  # Console applications
                  sudo, alacritty, byobu, ttf-fira-code, nvim, v2ray, aria2, proxychains, debtap, hugo, 
                  # Desktop Applications
                  dolphin, chromium, midori, calibre, libreoffice-fresh, qv2ray, redshift, vlc, juk, qemu, samba,
                  # C Development
                  _i-devel, gdb, clang,
                  # Clojure Development
                  leiningen, joker-bin, clj-kondo,
                  # Patches
                  pulseaudio-bluetooth
                ]
      stow: 
          stow: ./dot-files  
          target: ~/
          _: [alacritty, byobu SpaceVim zsh]
      yarn: [remark, remark-cli, remark-stringify, remark-frontmatter, wcwidth]

    oh-my-zsh:
      _i: shell
      _d:
        _b: 
          pacman: "zsh"
      _: '-c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
