#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
    
# All SpaceVim option below [option] section
# Manual Options goes last since it might be rewrite by layers. 
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # Add bootstrap functions
    bootstrap_before = 'boot#before'
    bootstrap_after = 'boot#after'
    # Disable relative number
    relativenumber = false

# UI
[[layers]]
    name = "colorscheme"

# Features
[[layers]]
    name = 'autocomplete'
    enable=true
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'git'

# [[layers]]
#  name = "gtags"
#  gtagslabel = "pygments"

[[layers]]
    name = 'leaderf'

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'VersionControl'

# Language specific
[[layers]]
    name = 'lang#clojure'

