#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
    
# All SpaceVim option below [option] section
# Manual Options goes last since it might be rewrite by layers. 
[options]
    # Appearance
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = true
    relativenumber = false
    statusline_separator = "nil"
    statusline_iseparator = "nil"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # Features
    filemanager = "defx"
    # Add bootstrap functions
    bootstrap_before = "boot#before"
    bootstrap_after = "boot#after"
    # Linters
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true
# UI
[[layers]]
    name = "colorscheme"

# Features

# Basics

[[layers]]
    name = "core"
    filetree_show_hidden = true

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

[[layers]]
    name = "git"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = "denite"

# Programming
[[layers]]
    name = "autocomplete"
    enable=true
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = "checkers"

# Language specific
[[layers]]
    name = "lang#markdown"

[[custom_plugins]] # Replacement for lang#clojure
    repo = "Olical/conjure"

[[layers]]
    name = "lang#c"
    enable_clang_syntax_highlight = true
    clang_executable = "/usr/bin/clang"
    libclang_path = "/usr/lib/libclang.so"
